day_97/admin_client/app/__init__.py
from flask import Flask, current_app
from app.service.api_client import ProductApi, AuthApi, UserApi, OrdersApi
from dotenv import load_dotenv
import os


load_dotenv()


def create_app():
    app = Flask(__name__)

    # add config
    app.config.from_object("app.config.Config")

    # api client
    auth_client = AuthApi(os.getenv("BASE_URI"))
    product_client = ProductApi(os.getenv("BASE_URI"))
    user_client = UserApi(os.getenv("BASE_URI"))
    order_client = OrdersApi(os.getenv("BASE_URI"))

    # import blueprint
    from app.routes.dashboard import dashboard_bp, init_dashboard
    from app.routes.login import login_bp, init_login
    from app.routes.product_management import product_bp, init_product
    from app.routes.user import user_bp, init_user
    from app.routes.orders import orders_bp, init_order

    # initialize routes
    init_login(auth_client)
    init_product(product_client)
    init_user(user_client)
    init_order(order_client)
    init_dashboard(user_client, order_client, product_client)

    app.register_blueprint(dashboard_bp, url_prefix="/dashboard/")
    app.register_blueprint(login_bp, url_prefix="/dashboard/login/")
    app.register_blueprint(product_bp, url_prefix="/dashboard/products/")
    app.register_blueprint(user_bp, url_prefix="/dashboard/users/")
    app.register_blueprint(orders_bp, url_prefix="/dashboard/orders/")



    

    return app

day_97/admin_client/app/routes/dashboard.py
from flask import Blueprint, render_template
from app.util import login_required
from app.service.api_client import OrdersApi, UserApi, ProductApi


user_client = None
order_client = None
product_client = None

dashboard_bp = Blueprint("dashboard", __name__)

def init_dashboard(user_api:UserApi, order_api:OrdersApi, product_api:ProductApi):
    global user_client, order_client, product_client
    user_client = user_api
    order_client = order_api
    product_client = product_api

@dashboard_bp.route("/", methods=["POST", "GET"])
@login_required
def home():

    res_user = user_client.get_all()
    res_order = order_client.get_all()
    res_product = product_client.get_all()

    data = {
        "user_count" : len(res_user),
        "order_count" : len(res_order), 
        "product_count" : len(res_product),
        "stock_count" : sum(item['stock'] or 0 for item in res_product),
        "lowest_stock" : [item for item in res_product if item['stock'] < 2 ]
    }

    return render_template("index.html", data = data, navigation=True)

day_97/admin_client/app/routes/login.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from app.service.api_client import AuthApi, ProductApi, UserApi


auth_client = None

def init_login(api_client_auth:AuthApi):
    global auth_client
    auth_client = api_client_auth

login_bp = Blueprint("login", __name__)

@login_bp.route("/", methods=["POST", "GET"])
def login():

    error = None
    if request.method == "POST":
        data = request.form
        if not data or "email" not in data or "password" not in data:
            error = "Invalid input"

        try:
            email = data["email"]
            password = data["password"]


            response_data = auth_client.login(email, password)

            session["token"] = response_data["token"]

            return redirect(url_for("dashboard.home"))
        except Exception as e:
            return redirect(url_for("login.login"))
            
    
    return render_template("login.html", error=error)

@login_bp.route("/logout")
def log_out():
    session.clear()
    return redirect(url_for("login.login"))

day_97/admin_client/app/routes/orders.py
from flask import Blueprint, render_template
from app.service.api_client import OrdersApi

orders_api = None

orders_bp = Blueprint("orders", __name__)


def init_order(orders_client:OrdersApi):
    global orders_api
    orders_api = orders_client

@orders_bp.route("/", methods=["GET", "POST"])
def home():
    orders = orders_api.get_all()    
    
    return render_template("orders.html", data = orders, navigation = True)  

day_97/admin_client/app/routes/product_management.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from app.util import login_required
from app.service.api_client import ProductApi

product_bp = Blueprint("product", __name__)

product_api = None

def init_product(api_client:ProductApi):
    global product_api
    product_api = api_client

@product_bp.route("/", methods=["POST", "GET"])
@login_required
def home():
    product_api.set_token(session["token"])
    
    if request.method == "POST":
        form_data = request.form

        if not form_data or "name" not in form_data or "price" not in form_data:
            flash("Missing important details.", "error")
        elif "id" not in form_data:   
            res = product_api.create(form_data.to_dict())
        else:
            id = form_data["id"]
            res = product_api.update(form_data.to_dict(), id)

    
    data = product_api.get_all()
    return render_template("products.html", data = data, navigation=True)

@product_bp.route("/delete/<int:product_id>", methods=['GET'])
@login_required
def delete(product_id):
    result = product_api.delete(product_id)

    if result["status"] == 200:
        flash("Product deleted successfully ✅", "success")
    elif result["status"] == 400:
        flash("Item not found ❌", "error")
    else:
        flash("Something went wrong. Please try again.", "error")

    return redirect(url_for("product.product"))


@product_bp.route("/search", methods=["GET"])
@login_required
def search():
    q = request.args.get("q", "").lower()

    if q == "" or q == " ":
        res = product_api.get_all()
    else:   
        res = product_api.search(q)

    return render_template("_products.html", data = res)

day_97/admin_client/app/routes/user.py
from flask import Blueprint, render_template, session, request, flash
from app.service.api_client import UserApi
from app.util import login_required

user_api = None

user_bp = Blueprint("user", __name__)

def init_user(api_client:UserApi):
    global user_api
    user_api = api_client

@user_bp.route("/", methods=["POST", "GET"])
@login_required
def home():
    user_api.set_token(session["token"])

    if request.method == "POST":
        form_data = request.form

        print(form_data)

        if not form_data or "name" not in form_data:
            flash("Name data not found")
        elif form_data["id"] == "":    
            result = user_api.create(form_data.to_dict())
        else:
            result = user_api.update(user_id=form_data["id"], data=form_data.to_dict())

        flash(result["message"])

    data = user_api.get_all()
    return render_template("users.html", data=data, navigation=True)


@user_bp.route("/search", methods=["GET"])
def search():
    q = request.args.get("q", "").lower()

    if q == "" or q == " ":
        res = user_api.get_all()
    else:   
        res = user_api.search(q)

    return render_template("_users.html", data = res)

day_97/admin_client/app/templates/_low_stock.html
{% if not data : %}
<tr>
  <td colspan="9" class="text-center">No results found</td>
</tr>
{% else %}
    {% for prod in data['lowest_stock'] :%}
    <tr>
        <td id="prod_id_{{prod.id}}">{{prod.id}}</td>
        <td id="prod_name_{{prod.id}}">{{prod.name}}</td>
        <td id="prod_price_{{prod.id}}">{{prod.price}}</td>
        <td id="prod_stock_{{prod.id}}">{{prod.stock}}</td>
    </tr>
    {% endfor %}
{% endif %}

day_97/admin_client/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>People Dashboard</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js"></script>
  
    <style>
      *{
        margin: 0;
        padding: 0;
      }
      /* General */
      body {
        background: linear-gradient(135deg, #fdfdfda1, #d0d795a1);
        font-family: "Inter", sans-serif;
        color: #333;
      }

      /* Navbar */
      .navbar {
        padding: 0.75rem 1rem;
      }
      .navbar-brand {
        font-weight: 700;
        font-size: 1.25rem;
        padding: 5px;
        border: 1px solid black;
        border-radius: 20px;
      }
      .nav-link {
        color: #6c757d !important;
        margin: 0 0.4rem;
        font-weight: 500;
        padding: 10px;
        border-radius: 20px;
        border-bottom: 1px solid rgba(245, 222, 179, 0);
      }

      .nav-link:hover {
        border-bottom: 1px solid black;
        color: white;
      }

      .nav-link.active {
        padding: 10px;
        border-radius: 20px;
        background-color: rgba(73, 108, 30, 0.459);
        color: white;
      }

      .nav-item.setting {
        padding: 3px;
        border-radius: 30px;
        background-color: white;
        margin-left: 10px;
      }

      .navbar-nav-2 {
        display: flex;
        flex-flow: row wrap;
        background-color: white;
        border-radius: 30px;
        padding: 3px;
        list-style-type: none;
      }

      /* Page Title */
      h3 {
        font-weight: 600;
        margin-bottom: 1.5rem;
      }

      /* Progress Stats */
      .progress {
        height: 0.6rem;
        border-radius: 1rem;
        background-color: #e9ecef;
        box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.05);
      }
      .progress-bar {
        border-radius: 1rem;
        transition: width 0.4s ease;
      }
      .row > .col-md-3 p {
        margin-bottom: 0.4rem;
        font-weight: 500;
      }

      /* Search box */
      .search-1{
        padding: 10px;
        border-radius: 20px 20px 0px 0px;
      }

      .search-1 button{
        border: 0.5px solid rgba(128, 128, 128, 0.728);
      }

      .search-2{
        padding: 10px;
      }

      .search-2 button{
        border-radius: 15px;
      }

      input.form-control {
        border-radius: 2rem;
        padding-left: 1.2rem;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
        border: 1px solid #ddd;
      }
      input.form-control:focus {
        border-color: #ffcd39;
        box-shadow: 0 0 0 0.2rem rgba(255, 193, 7, 0.25);
      }

      .dropdown button{
        border-radius: 20px;
      }

      .search-input {
        width: 420px;
      }

      /* Table */
      .table {
        background: #fff;
        border-radius: 1rem;
        overflow: hidden;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
      }
      .table th {
        font-weight: 600;
        color: #6c757d;
        font-size: 0.9rem;
      }
      .table td {
        vertical-align: middle;
        font-size: 0.95rem;
      }
      .table-hover tbody tr:hover {
        background-color: #fffbea;
      }

      /* Highlighted row */
      .highlight {
        background-color: #fff7d1 !important;
      }

      /* Avatars */
      .avatar {
        width: 36px;
        height: 36px;
        border-radius: 50%;
        object-fit: cover;
        margin-right: 0.6rem;
        border: 2px solid #f1f1f1;
      }

      /* Status tags */
      .status a {
        border-radius: 1rem;
        font-size: 0.8rem;
        font-weight: 600;
        text-align: center;
        margin: 10px;
        padding: 10px 20px;
        border: 1px solid rgba(128, 128, 128, 0.582);
        text-decoration: none;
      }

      .status.invited a {
        background-color: #eaf7ef;
        color: #198754;
      }
      .status.absent a {
        background-color: #fcebea;
        color: #dc3545;
      }
    </style>
    
  </head>
  <body>
    <!-- Navbar -->

    {% if navigation : %}
    <nav class="navbar navbar-expand-lg navbar-light shadow-sm">
      <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="#">My Shop</a>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li>
            <ul class="navbar-nav-2 ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('dashboard.home')}}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{{url_for('user.home')}}">Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('product.home')}}">Products</a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('orders.home')}}">Orders</a></li>
            </ul>
          </li>
          <li class="nav-item setting">
            <a class="nav-link" href="{{url_for('login.log_out')}}">Log-out</a>
          </li>
        </ul>
      </div>
    </nav>
    {% endif %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  
</body>
</html>

day_97/admin_client/app/templates/products.html
{% extends "base.html" %} {% block content %}
<div class="container py-4">
  <h3 class="mb-4">Products</h3>
  <style>
    .pop-up-container {
      background: linear-gradient(135deg, #fdfdfd, #d0d795);
      position: fixed;
      display: none;
      justify-content: center;
      z-index: 1;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      padding: 20px;
      overflow-y: scroll;
    }
  </style>

  <!-- Add Product -->
  <div class="pop-up-container" id="pop-up-container">
    <div class="pop-up col-10">
      <form
        id="product_form"
        action="{{url_for('product.home')}}"
        method="post"
        class="row d-flex justify-content-center"
      >
        <div class="d-flex justify-content-between">
          <h2 id="pop-title">Add New Product</h2>
          <div class="d-flex">
            <button class="btn btn-outline-primary">Save</button>
            <button type="button" id="form_delete_btn" class="btn btn-outline-danger text-center" style="display: none;"><a href="" id="form_link">Delete</a></button>
            <button
              type="button"
              onclick="popProduct()"
              class="btn btn-outline-danger"
            >
              Cancel
            </button>
          </div>
        </div>
        <div class="col-3 p-2 m-2">
          <div class="border d-flex row border p-3" style="border-radius: 20px">
            <p class="fw-bold f-3 p-2 border-bottom">Thumbnail</p>
            <img id="form_image" src="" alt="" width="150" height="150" />
            <p class="text-center fs-9 mt-2">Only *.png, *.jpg, *.jpeg</p>
          </div>
          <div
            class="border d-flex row border p-3 mt-2"
            style="border-radius: 20px"
          >
            <p class="fw-bold f-3 border-bottom p-2">Product Details</p>
            <label for="">Categories</label>
            <div class="dropdown border mt-2">
              <button
                class="btn btn-light dropdown-toggle"
                type="button"
                id="dropdownMenuButton"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                style="width: 100%"
              >
                Select an option
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-8 p-2 m-2">
          <div class="border d-flex row border p-3" style="border-radius: 20px">
            <p class="fw-bold f-3 p-2 border-bottom">General</p>
            <input type="number" name="id" id="form_id" style="display: none" />
            <label for="">Product Name</label>
            <input
              class="border rounded p-2"
              type="text"
              name="name"
              id="form_name"
            />
            <p class="fs-9">Product name is required and must be unique.</p>
            <label for="">Description</label>
            <textarea
              class="border rounded p-2"
              name="description"
              id="form_description"
            ></textarea>
          </div>
          <div
            class="border d-flex row border p-3 mt-2"
            style="border-radius: 20px"
          >
            <p class="fw-bold f-3 p-2 border-bottom">Pricing</p>
            <label for="">Price</label>
            <input
              class="border rounded p-2"
              type="text"
              name="price"
              id="form_price"
            />
            <p class="fs-9">Set base price.</p>

            <label for="">Stock</label>
            <input
              class="border rounded p-2"
              type="text"
              name="stock"
              id="form_stock"
            />
            <p class="fs-9">Set items count.</p>

            <p class="fw-bold f-3 p-2 border-bottom">Discount Type</p>
            <div
              class="btn-group"
              role="group"
              aria-label="Basic checkbox toggle button group"
            >
              <input
                type="checkbox"
                class="btn-check"
                id="btncheck1"
                autocomplete="off"
              />
              <label
                class="btn btn-outline-primary rounded-pill m-2"
                for="btncheck1"
                >Checkbox 1</label
              >

              <input
                type="checkbox"
                class="btn-check"
                id="btncheck2"
                autocomplete="off"
              />
              <label
                class="btn btn-outline-primary rounded-pill m-2"
                for="btncheck2"
                >Checkbox 2</label
              >

              <input
                type="checkbox"
                class="btn-check"
                id="btncheck3"
                autocomplete="off"
              />
              <label
                class="btn btn-outline-primary rounded-pill m-2"
                for="btncheck3"
                >Checkbox 3</label
              >
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>


  <!-- Search -->
  <div class="d-flex search-m justify-content-between">
    <div class="d-flex gap-4 search-1">
      <div class="dropdown">
        <button
          class="btn btn-light dropdown-toggle"
          type="button"
          id="dropdownMenuButton"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Product Type
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
      <div class="search-input">
        <form
          hx-get="{{url_for('product.search')}}"
          hx-target="#results"
          hx-trigger="keyup changed delay:300ms"
          class="d-flex justify-content-between"
        >
          <input
            type="text"
            name="q"
            class="form-control"
            placeholder="Search..."
          />
          <button class="btn btn-light" style="margin-left: 20px" type="submit">
            Search
          </button>
        </form>
      </div>
    </div>
    <div class="d-flex gap-2 search-2">
      <button class="btn btn-light" onclick="popProduct()">Add Product</button>
      <button class="btn btn-light">=</button>
      <button class="btn btn-light">Export</button>
    </div>
  </div>

  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-hover align-middle">
      <thead class="table-light">
        <tr>
          <th></th>
          <th>ID</th>
          <th>Product Name</th>
          <th>Price</th>
          <th>Stock</th>
          <th>CreatedAt</th>
          <th>UpdateAt</th>
          <th class="text-center">Action</th>
        </tr>
      </thead>
      <tbody id="results">
        {% include "_products.html" %}
      </tbody>
    </table>
  </div>
</div>

<script>
  function popProduct() {
    var container = document.querySelector("#pop-up-container");
    var form = document.querySelector("#product_form");
    var title = document.querySelector("#pop-title");

    var form_delete_btn = document.querySelector("#form_delete_btn");


    var form_id = document.querySelector("#form_id");
    var form_name = document.querySelector("#form_name");
    var form_description = document.querySelector("#form_description");
    var form_price = document.querySelector("#form_price");
    var form_stock = document.querySelector("#form_stock");

    form_delete_btn.style.display = "none";
    form_id.value = ""
    form_name.value = ""
    form_description.value = ""
    form_price.value = ""
    form_stock.value = ""

    title.textContent = "Add New Product";

    if (container.style.display == "flex") {
      container.style.display = "none";
    } else {
      container.style.display = "flex";
    }
  }

  function updateProduct(id) {
    var container = document.querySelector("#pop-up-container");
    var title = document.querySelector("#pop-title");


    title.textContent = "Update Product";

    var name = document.querySelector("#prod_name_" + id).textContent;
    var description = document.querySelector(
      "#prod_description_" + id
    ).textContent;
    var price = document.querySelector("#prod_price_" + id).textContent;
    var stock = document.querySelector("#prod_stock_" + id).textContent;
    var img = document.querySelector("#prod_image_" + id).textContent;

    var form_delete_btn = document.querySelector("#form_delete_btn");
    var form_link = document.querySelector("#form_link");

    form_delete_btn.style.display = "block";
    form_link.href = `/dashboard/products/delete/${id}`;

    var form_id = document.querySelector("#form_id");
    var form_name = document.querySelector("#form_name");
    var form_description = document.querySelector("#form_description");
    var form_price = document.querySelector("#form_price");
    var form_stock = document.querySelector("#form_stock");
    var form_image = document.querySelector("#form_image");

    form_id.value = id;
    form_name.value = name;
    form_description.value = description;
    form_price.value = price;
    form_stock.value = stock;

    form_image.src = img;

    container.style.display = "flex";

    console.log(price);
  }
</script>
{% endblock %}

day_97/admin_client/app/templates/users.html
{% extends "base.html" %}
{% block content %}
<div class="container py-4">
  <h3 class="mb-4">Users</h3>

  <style>
    .pop-up-container {
      background: linear-gradient(135deg, #fdfdfd, #d0d795);
      position: fixed;
      display: none;
      justify-content: center;
      z-index: 1;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      padding: 20px;
      overflow-y: scroll;
    }
  </style>

  <!-- Add Product -->
  <div class="pop-up-container" id="pop-up-container">
    <div class="pop-up col-10">
      <form id="product_form" action="{{url_for('user.home')}}" method="post" class="row d-flex justify-content-center">
        <div class="d-flex justify-content-between">
          <h2 id="pop-title">Add New User</h2>
          <div class="d-flex">
            <button class="btn btn-outline-primary">Save</button>
            <button type="button" id="form_delete_btn" class="btn btn-outline-danger text-center"
              style="display: none;"><a href="" id="form_link">Delete</a></button>
            <button type="button" onclick="popUser()" class="btn btn-outline-danger">
              Cancel
            </button>
          </div>
        </div>
        <div class="col-3 p-2 m-2">
          <div class="border d-flex row border p-3" style="border-radius: 20px">
            <p class="fw-bold f-3 p-2 border-bottom">Thumbnail</p>
            <img src="" alt="" width="150" height="150" />
            <p class="text-center fs-9 mt-2">Only *.png, *.jpg, *.jpeg</p>
          </div>
          <div class="border d-flex row border p-3 mt-2" style="border-radius: 20px">
            <p class="fw-bold f-3 border-bottom p-2">Product Details</p>
            <label for="">Categories</label>
            <div class="dropdown border mt-2">
              <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false" style="width: 100%">
                Select an option
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-8 p-2 m-2">
          <div class="border d-flex row border p-3" style="border-radius: 20px">
            <p class="fw-bold f-3 p-2 border-bottom">General</p>
            <input type="number" name="id" id="form_id" style="display: none" />
            <label for="">User Name</label>
            <input class="border rounded p-2" type="text" name="name" id="form_name" />
            <p class="fs-9">User name is required and must be unique.</p>
            <label for="">User Email</label>
            <input class="border rounded p-2" type="email" name="email" id="form_email" />
            <p class="fs-9">Email must not be use on same account.</p>
            <label for="">Password</label>
            <input class="border rounded p-2" type="text" name="password" id="form_password" value="admin-12345" />
            <p class="fs-9" id="form_password_message">Password will be set as defualt.</p>

          </div>
          <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" name="form_role" class="btn-check" id="btncheck1" value="ADMIN" autocomplete="off" />
            <label class="btn btn-outline-primary rounded-pill m-2" for="btncheck1">Admin</label>

            <input type="radio" name="form_role" class="btn-check" id="btncheck2" value="MODERATOR"
              autocomplete="off" />
            <label class="btn btn-outline-primary rounded-pill m-2" for="btncheck2">Moderator</label>

            <input type="radio" name="form_role" class="btn-check" id="btncheck3" value="USER" autocomplete="off" />
            <label class="btn btn-outline-primary rounded-pill m-2" for="btncheck3">User</label>
          </div>

        </div>
      </form>
    </div>
  </div>


  <!-- Search -->
  <div class="d-flex search-m justify-content-between">
    <div class="d-flex gap-4 search-1">
      <div class="dropdown">
        <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Role
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
            <div class="search-input">
        <form
          hx-get="{{url_for('user.search')}}"
          hx-target="#results"
          hx-trigger="keyup changed delay:300ms"
          class="d-flex justify-content-between"
        >
          <input
            type="text"
            name="q"
            class="form-control"
            placeholder="Search..."
          />
          <button class="btn btn-light" style="margin-left: 20px" type="submit">
            Search
          </button>
        </form>
      </div>
    </div>
    <div class="d-flex gap-2 search-2 ">
      <button class="btn btn-light" onclick="popUser()">+</button>
      <button class="btn btn-light">=</button>
      <button class="btn btn-light">Export</button>
    </div>
  </div>

  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-hover align-middle">
      <thead class="table-light">
        <tr>
          <th></th>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>CreatedAt</th>
          <th>UpdateAt</th>
          <th class="text-center">Status</th>
        </tr>
      </thead>
      <tbody id="results">
        {% include "_users.html" %}
      </tbody>
    </table>
  </div>
</div>
<script>
  function popUser() {
    var container = document.querySelector("#pop-up-container");
    var form = document.querySelector("#product_form");
    var title = document.querySelector("#pop-title");

    var form_delete_btn = document.querySelector("#form_delete_btn");


    var form_id = document.querySelector("#form_id");
    var form_name = document.querySelector("#form_name");
    var form_email = document.querySelector("#form_email");
    var form_password = document.querySelector("#form_password");

    form_password.style.display = "block";
    form_password.type = "text";
    form_delete_btn.style.display = "none";
    form_id.value = ""
    form_name.value = ""
    form_email.value = ""

    title.textContent = "Add New User";

    if (container.style.display == "flex") {
      container.style.display = "none";
    } else {
      container.style.display = "flex";
    }
  }

  function updateUser(id) {
    var container = document.querySelector("#pop-up-container");
    var title = document.querySelector("#pop-title");


    title.textContent = "Update User";

    var name = document.querySelector("#user_name_" + id).textContent;
    var email = document.querySelector(
      "#user_email_" + id
    ).textContent;
    var role = document.querySelector("#user_role_" + id).textContent;

    var form_delete_btn = document.querySelector("#form_delete_btn");
    var form_link = document.querySelector("#form_link");

    form_delete_btn.style.display = "block";
    form_link.href = `/dashboard/users/delete/${id}`;

    var form_id = document.querySelector("#form_id");
    var form_name = document.querySelector("#form_name");
    var form_role = document.querySelector("#form_role");
    var form_email = document.querySelector("#form_email");
    var form_password = document.querySelector("#form_password");

    form_id.value = id;
    form_name.value = name;
    form_email.value = email;

    form_email.readOnly = true;
    // form_password.style.display = "none";
    form_password.readOnly = true;
    form_password.type = "password";

    setRole(role)

    container.style.display = "flex";
  }

  function setRole(role) {
    role = role.toLowerCase()

    const radios = document.querySelectorAll("input[name='form_role']")

    radios.forEach(radio => {
      radio.checked = radio.value.toLowerCase() === role;
    })
  }
</script>
{% endblock %}