day_97/client/app/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os

load_dotenv()

def create_app():

    app = Flask(__name__)

    app.config.from_object("app.config.Config")

    from app.routes.shop import shop_bp, init_shop
    from app.routes.login import login_bp, init_login
    from app.routes.signup import signup_bp, init_signup
    from app.routes.cart import cart_bp, init_cart
    from app.routes.profile import profile_bp, init_profile

    from app.service.api_client import ProductApi
    from app.service.api_client import AuthApi
    from app.service.api_client import UserApi
    from app.service.api_client import CartApi
    from app.service.api_client import PaymentApi

    product_api = ProductApi(os.getenv("BASE_URI"))
    auth_api = AuthApi(os.getenv("BASE_URI"))
    user_api = UserApi(os.getenv("BASE_URI"))
    cart_api = CartApi(os.getenv("BASE_URI"))
    payment_api = PaymentApi(os.getenv("BASE_URI"))

    init_shop(product_api)
    init_login(auth_api)
    init_signup(user_api)
    init_cart(cart_api, payment_api)
    init_profile(user_api, cart_api)

    app.register_blueprint(shop_bp)
    app.register_blueprint(login_bp, url_prefix="/login/")
    app.register_blueprint(signup_bp, url_prefix="/signup/")
    app.register_blueprint(cart_bp, url_prefix="/cart/")
    app.register_blueprint(profile_bp, url_prefix="/profile/")

    return app

day_97/client/app/routes/cart.py
from flask import Blueprint, render_template, current_app, jsonify, session, request, redirect, url_for
from app.service.api_client import CartApi, PaymentApi
from app.util import login_required, is_login
import base64, requests

cart_api = None
payment_api = None

cart_bp = Blueprint("cart", __name__)


def init_cart(cart_client:CartApi, payment_client:PaymentApi):
    global cart_api, payment_api
    cart_api = cart_client
    payment_api = payment_client

@cart_bp.route("/", methods=["GET", "POST"])
@login_required
def home():
    cart_api.set_token(session["token"])

    result = cart_api.get_by_id('active')

    if "status" in result:
        if result['status'] == 402 or result['status'] == 403:
            return redirect(url_for('login.log_out'))
        elif result['status'] == 404:
            return render_template("cart.html", data = [], is_login = is_login())
    else:
        return render_template("cart.html", data = result, is_login = is_login())


@cart_bp.route("/add_cart/<int:product_id>")
@login_required
def add_item_cart(product_id):
    cart_api.set_token(session['token'])

    data = {"product_id" : product_id}

    result = cart_api.add_item(data)

    return redirect(url_for('cart.home'))

@cart_bp.route("/update/<int:item_id>", methods=["GET"])
@login_required
def update_cart(item_id):
    cart_api.set_token(session["token"])

    q = request.args.get("quantity", "").lower()

    if q != "" or q != " ":  
        data = {"product_id" : item_id, "quantity" : q}
        res = cart_api.add_item(data=data)

    result = cart_api.get_by_id()

    return render_template("_shopping_cart.html", data = result)

@cart_bp.route("/pay_cart/<int:cart_id>")
@login_required
def pay_cart(cart_id):
    payment_api.set_token(session["token"])

    data = {"return_url" : url_for('cart.success', cart_id=cart_id, _external = True), "cancel_url" : url_for('cart.cancelled', _external = True)}
    result = payment_api.create_order(cart_id, data)
    
    return redirect(result["url"])


@cart_bp.route("/success/<int:cart_id>")
@login_required
def success(cart_id):
    payment_api.set_token(session['token'])
    
    data = {
        "token" : request.args.get("token"),
        "payer_id" : request.args.get("PayerID"),
        "cart_id" : cart_id
    }

    result = payment_api.capture_order(data)

    print(result)
    return "success"

@cart_bp.route("/cancelled")
@login_required
def cancelled():
    return "cancelled"

day_97/client/app/routes/login.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from app.service.api_client import AuthApi


auth_client = None

def init_login(api_client_auth:AuthApi):
    global auth_client
    auth_client = api_client_auth

login_bp = Blueprint("login", __name__)

@login_bp.route("/", methods=["POST", "GET"])
def login():

    error = None
    if request.method == "POST":
        data = request.form
        if not data or "email" not in data or "password" not in data:
            error = "Invalid input"

        try:
            email = data["email"]
            password = data["password"]

            response_data = auth_client.login(email, password)

            session["token"] = response_data["token"]

            print("Hello")
            return redirect(url_for("shop.home"))
        except Exception as e:
            print(e)
            return redirect(url_for("login.login"))
            
    
    return render_template("login.html", error=error)

@login_bp.route("/logout")
def log_out():
    session.clear()
    return redirect(url_for("login.login"))

day_97/client/app/routes/profile.py
from flask import Blueprint, render_template, url_for, redirect, session, request
from app.service.api_client import UserApi, CartApi
from app.util import is_login, login_required

user_client = None
cart_client = None

profile_bp = Blueprint('profile' , __name__)

def init_profile(user_api:UserApi, cart_api:CartApi):
    global user_client, cart_client
    user_client = user_api
    cart_client = cart_api

@profile_bp.route('/', methods=["GET"])
@login_required
def home():
    user_client.set_token(session['token'])
    cart_client.set_token(session['token'])

    user = user_client.get_by_token()
    cart = cart_client.get_by_id('paid')
    return render_template('profile.html', user = user, orders = cart, is_login = is_login())   

@profile_bp.route('/<int:user_id>', methods=["GET", "POST"])
@login_required
def update_profile(user_id):
    print(user_id)
    data = request.form.to_dict()
    

    user_client.set_token(session['token'])

    user = user_client.update(data, user_id)

    return redirect(url_for('profile.home'))

day_97/client/app/routes/shop.py
from flask import Blueprint, render_template, session
from app.service.api_client import ProductApi
from app.util import login_required, is_login

product_api = None

shop_bp = Blueprint("shop", __name__)

def init_shop(product_client:ProductApi):
    global product_api
    product_api = product_client


@shop_bp.route("/", methods=["GET", "POST"])
def home():

    products = product_api.get_all()
    return render_template('main.html', data = products, is_login = is_login())

day_97/client/app/routes/signup.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from app.service.api_client import UserApi


user_client = None

def init_signup(api_client_user:UserApi):
    global user_client
    user_client = api_client_user

signup_bp = Blueprint("signup", __name__)

@signup_bp.route("/", methods=["POST", "GET"])
def home():

    error = None
    if request.method == "POST":
        data = request.form
        if not data or "email" not in data or "password" not in data or "name" not in data:
            error = "Invalid input"

        try:
            response_data = user_client.create(data.to_dict())

            return redirect(url_for("shop.home"))
        except Exception as e:
            return redirect(url_for("login.login"))
            
    
    return render_template("signup.html", error=error)

day_97/client/app/templates/_shopping_cart.html
{% if not data :%}

<div>
  <p>No cart data</p>
</div>

{% else %}
<div id="shop-cart">
  <div class="cart-title">
    <h1>Shopping Cart</h1>
  </div>
  <div class="cart-table">
    {% for item in data[0]['items'] :%}
    <div class="t-item">
      <div>
        <p class="t-item-title">Product Details</p>
        <img src="{{item.image_uri}}" width="150" height="150" alt="" />
        <div class="t-details">
          <p class="c-item-title">{{item.name}}</p>
          <a class="c-remove-btn" href="">Remove</a>
        </div>
      </div>
      <div>
        <div>
          <p class="t-item-title">Quantity</p>

          <form hx-get="{{url_for('cart.update_cart', item_id = item.id)}}" hx-target="#shopping-cart"
            hx-trigger="input delay:100ms" class="c-quantity t-details-container">
            <input type="number" id="quantity_{{item.id}}" name="quantity" min="1" max="9" step="1"
              value="{{item.quantity}}" style="color: black; padding: 5px; text-align: center;" />
          </form>
        </div>
        <div>
          <p class="t-item-title">Price</p>
          <div class="t-details-container">
            <p>Php {{item.price}}</p>
          </div>
        </div>
        <div>
          <p class="t-item-title">Total</p>
          <div class="t-details-container">
            <p>Php {{item.total}}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="order-summary">
  <div class="summary-title">
    <h2>Order Summary</h2>
  </div>
  <div class="summary-totals">
    <div class="summary-item">
      <h3>Total Items</h3>
      <p>{{data[0].item_count}}</p>
    </div>
    <div class="summary-item">
      <h3>Sub Total</h3>
      <p>Php {{data[0].sub_total}}</p>
    </div>
    <div class="summary-item">
      <h3>Shipping</h3>
      <p>Php {{data[0].shipping}}</p>
    </div>
    <div class="summary-item">
      <h2>Total</h2>
      <p id="price-total">Php {{data[0].total}}</p>
    </div>
  </div>
  <div style="display: flex; flex-flow: row wrap;">
    <p style="font-size: 14px; margin-bottom: 5px">
      We only accept PayPal payments
    </p>
    <br>
    <a id="payment" type="button" href="{{url_for('cart.pay_cart', cart_id = data[0].id)}}""> <img width=" 15"
      src="/static/paypal.png" alt="">Payment</a>
    <p id="result-message"></p>
  </div>
</div>

{% endif %}

day_97/client/app/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      * {
        padding: 0;
        margin: 0;
      }

      .container {
        display: flex;
        flex-flow: column wrap;
        justify-content: center;
        align-items: center;
        width: 100%;
        margin-bottom: 20px;
        margin-top: 20px;
      }

      nav {
        display: flex;
        flex-flow: row wrap;
        justify-content: space-between;
        align-content: center;
        align-items: center;
        width: 900px;
        padding: 20px;
      }

      nav div {
        display: flex;
        flex-flow: row wrap;
        align-items: center;
        gap: 10px;
        background-color: bisque;
        border-radius: 20px;
        padding: 0px 20px 0px 20px;
      }

      nav div a {
        font-size: 15px;
        font-weight: bold;
        padding: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        border: none;
        background: none;
      }
      nav div a img{
        width: 20px;
      }

      .categories {
        display: flex;
        justify-content: space-between;
        gap: 20px;
        width: 900px;
      }

      .categories button {
        background: none;
        border: none;
        border-bottom: 3px solid black;
        margin: 20px;
        padding: 10px;
        width: 110px;
        transition: 0.6s ease-out;
        font-weight: bold;
        text-transform: uppercase;
      }

      .categories button:hover{
        border-bottom: 3px solid blue;
        color: rgb(31, 211, 43);
      }

      #user_image {
        width: 20px;
        height: 20px;
        border-radius: 50px;
        margin-left: 10px;
        padding: 5px;
        border: 1px solid black;
      }

      #brand{
        font-weight: bolder;
        text-transform: uppercase;
        font-size: 20px;
      }

      .nav-item{
        text-decoration: none;
        color: black;
        font-weight: bolder;
        font-family: 'Courier New', Courier, monospace;
        font-size: 16px;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js"></script>
  </head>
  <body>
    <section class="container">
      <nav>
        <p id="brand">Shop</p>
        <div>
          <a href="{{url_for('shop.home')}}" class="nav-item">Home</a>
          {% if not is_login :%}
          <a href="{{url_for('login.login')}}" class="nav-item">Login</a>
          <a href="{{url_for('signup.home')}}" class="nav-item">Sign-up</a>
          {% else %}
          <a href="{{url_for('cart.home')}}" class="nav-item"><img src="/static/shopping-cart.png" alt=""></a>
          <a href="{{url_for('profile.home')}}" id="user_image"><img src="/static/user.svg" alt="" srcset=""></a>
          {% endif %}
        </div>
      </nav>
      <div class="categories">
        <button>Womens</button>
        <button>Mens</button>
        <button>Bags</button>
        <button>Dresses</button>
        <button>Shoes</button>
      </div>
    </section>

    {% block content %}
    {% endblock%}

    <style>
      .footer{
        display: flex;
        justify-content: space-between;
        flex-flow: row wrap;
        padding: 20px;
        background-color: beige;
      }

      .footer > div{
        padding: 20px;
        display: flex;
        flex-flow: column wrap;
      }

      .footer > :first-child{
        width: 400px;
      }

      .footer > :first-child p {
        margin-top: 10px;
        font-size: 18px;
      }

      .footer > :first-child button {
        font-size: 15px;
        font-weight: bolder;
        color: white;
        background: black;
        border: 1px solid gray;
        width: 120px;
        padding: 10px;
        margin-top: 20px;
      }

      .footer > :last-child, .f-categories {
        width: 200px;
        border-left: 1px solid black;
      }

      .f-categories > div{
        padding-top: 10px;
        display: flex;
        flex-flow: column wrap;
        gap: 5px;
      }

      .f-categories a{
        text-decoration: none;
        color: black;
      }
    </style>
    <section class="container">
      <div class="footer">
        <div>
          <h2>Shop Now</h2>
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem, nemo vel odit dolorum animi quod.</p>
          <button>Sign-up</button>
        </div>
        <div class="f-categories">
          <h4>Categories</h4>
          <div>
            <a href="">Womens</a>
            <a href="">Mens</a>
            <a href="">Shoes</a>
            <a href="">Bags</a>
            <a href="">Dresses</a>
          </div>
        </div>
        <div>
          <h4>Contacts</h4>
          <a href="">
            <img src="" alt="">
          </a>
          <a href="">
            <img src="" alt="">
          </a>
          <a href="">
            <img src="" alt="">
          </a>
        </div>
      </div>
    </section>
  </body>
</html>

day_97/client/app/templates/cart.html
{% extends "base.html"%} {% block content %}

<style>
  #shopping-cart {
    display: flex;
  }

  #shopping-cart > :first-child {
    padding: 20px;
    width: 600px;
  }

  .cart-title {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-bottom: 20px;
    margin-bottom: 10px;
  }

  .cart-table {
    width: 600px;
    display: flex;
    flex-flow: row wrap;
  }

  .cart-table .t-item {
    display: flex;
    flex-flow: row wrap;
    padding: 10px;
    border: 1px solid gray;
    border-radius: 20px;
  }

  .t-item {
    margin-bottom: 10px;
  }

  .t-item > :first-child {
    padding: 20px;
  }

  .t-item > :last-child > div {
    padding: 20px;
  }

  .t-item > :first-child > div {
    display: flex;
    flex-flow: column wrap;
    width: 350px;
    gap: 10px;
  }

  .t-details-container {
    text-align: center;
  }

  .c-item-title {
    font-weight: bold;
    font-size: 18px;
    margin-bottom: 10px;
  }

  .c-remove-btn {
    text-decoration: none;
  }

  .c-quantity > * {
    padding: 10px;
    font-size: 20px;
    font-weight: bolder;
    border-radius: 5px;
    border: none;
    background: none;
    width: 40px;
    height: 40px;
  }

  .c-quantity > label {
    border: 1px solid black;
    border-radius: 5px;
    font-size: 15px;
  }

  .t-item-title {
    font-weight: bolder;
    color: gray;
    font-size: 20px;
    margin-bottom: 20px;
    border-bottom: 1px solid black;
    padding-bottom: 10px;
  }

  .t-details {
    margin-top: 20px;
  }

  .shopping-cart > :last-child {
    padding: 20px;
    width: 200px;
  }

  .summary-title {
    margin-bottom: 10px;
  }
</style>
<style>
  .order-summary {
    display: flex;
    flex-flow: column wrap;
    justify-content: space-between;
    height: 450px;
    width: 200px;
    gap: 20px;
  }
  .summary-item h3 {
    color: gray;
  }

  .summary-item p {
    margin-top: 10px;
    color: gray;
  }

  .summary-totals {
    display: flex;
    flex-flow: column wrap;
    gap: 20px;
  }

  #price-total {
    color: black;
    font-weight: bolder;
  }

  input[type="number"] {
    position: relative;
    padding-right: 30px; /* Space for custom buttons */
  }

  input[type="number"]::-webkit-inner-spin-button,
  input[type="number"]::-webkit-outer-spin-button {
    opacity: 1;
  }

  #paypal-button-container{
    width: 100%;
  }

  #payment {
    border: 1px solid black;
    text-decoration: none;
    padding: 10px 5px 10px 5px;
    border-radius: 5px;
  }
</style>
<section class="container">
  <div id="shopping-cart">
    {% include "_shopping_cart.html"%}
  </div>
</section>

{% endblock %}

day_97/client/app/templates/login.html
{% extends "base.html" %} {% block content %}

<style>
  .login {
    width: 300px;
    padding: 20px;
    border: 2px solid gray;
    margin: 20px;
    height: fit-content;
    box-shadow: 5px 10px 0px 0px gray;
  }

  .login-form {
    display: flex;
    flex-flow: column wrap;
  }

  .login-form * {
    margin-top: 20px;
  }

  .login-form input {
    border-top: 0px;
    border-left: 0px;
    border-right: 0px;
    padding: 10px;
  }

  .login-form input:focus {
    box-shadow: none;
    border-top: 0px;
    border-left: 0px;
    border-right: 0px;
    outline: none;
  }

  .login-form button {
    margin-top: 20px;
    padding: 10px;
  }
</style>
<section
  class="w-100 d-flex justify-content-center align-items-center container"
  style="height: 600px"
>
  <div class="login">
    <h2>Login</h2>
    <form action="{{url_for('login.login')}}" method="post" class="login-form">
      <input type="text" name="email" placeholder="Email" />
      <input type="password" name="password" placeholder="Password" />
      {% if error %}
      <p>{{error}}</p>
      {% endif %}
      <button>Login</button>
    </form>
  </div>
</section>

{% endblock %}

day_97/client/app/templates/main.html
{% extends "base.html"%}
{% block content %}
<style>
  .main-item {
    display: flex;
    flex-flow: row wrap;
    width: 800px;
    border: 1px solid black;
    padding: 25px;
    gap: 20px;
  }

  .main-img {
    padding: 20px;
    background-color: blanchedalmond;
    border-radius: 20px;
  }

  .main-img img {
    width: 200px;
    border-radius: 10px;
  }

  .main-description {
    width: 500px;
  }

  .m-item-title {
    text-transform: uppercase;
    font-size: 40px;
  }

  .m-item-description {
    font-size: 20px;
    color: gray;
  }

  .m-item-price {
    font-weight: bolder;
    font-size: 30px;
    color: rgb(183, 165, 29);
  }

  .m-btn-cart {
    background-color: black;
    text-transform: uppercase;
    color: white;
    width: 150px;
    padding: 10px 20px 10px 20px;
    margin-top: 40px;
    font-weight: bolder;
    text-decoration: none;
  }

  .m-btn-cart:hover {
    background: rgb(38, 167, 38);
    border: 2px solid gray;
    color: black;
  }
</style>
<style>
  .items {
    display: flex;
    flex-flow: row wrap;
    justify-content: space-around;
    padding: 10px;
    width: 900px;
    gap: 20px;
  }

  .item {
    width: 200px;
    border: 1px solid rgb(179, 137, 137);
    padding: 20px;
    display: flex;
    flex-flow: column wrap;
    justify-content: space-evenly;
  }

  .item-image {
    text-align: center;
    padding: 5px;
    border-radius: 20px;
    background-color: gray;
    width: 190px;
    overflow: hidden;
  }

  .item-image img {
    width: 180px;
    border-radius: 10px;
  }

  .description {
    margin-top: 10px;
  }

  .item-description {
    font-size: 13px;
    color: gray;
  }

  .item-price {
    font-size: 20px;
    font-weight: bold;
    margin-top: 5px;
  }

  .add-btn {
    margin-top: 10;
    padding: 10px;
    background-color: black;
    color: white;
    text-transform: uppercase;
    text-decoration: none;
  }
</style>

{% if not data :%}
<section class="container" style="height: 400px;">
  <h2>Shop server is not running</h2>
</section>
{% else :%}
<section class="container">
  <div class="main-item">
    <div class="main-img">
      <img src="{{data[0].image_uri}}" alt="">
    </div>
    <div class="main-description">
      <h2 class="m-item-title">{{data[0].name}}</h2>
      <p class="m-item-description">{{data[0].description}}</p>
      <p class="m-item-price">{{data[0].price}}</p>
      <br>
      <a type="button" class="m-btn-cart" href="{{url_for('cart.add_item_cart', product_id = data[0].id)}}">Add to Cart</a>
    </div>
  </div>
</section>
<section class="container">
  <div class="items">
    {% for item in data[1:8]%}
    <div class="item">
      <div class="item-image">
        <img src="{{item.image_uri}}" alt="" />
      </div>
      <div class="description">
        <h2 class="item-title">{{item.name}}</h2>
        <p class="item-description">
          {{item.description}}
        </p>
      </div>
      <div>
        <p class="item-price">{{item.price}}</p>
        <br>
        <a type="button" class="add-btn" href="{{url_for('cart.add_item_cart', product_id = item.id)}}">Add to Cart</a>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endif %}
{% endblock %}

day_97/client/app/templates/profile.html
{% extends "base.html"%} {% block content %}
<style>
  .user-block {
    display: flex;
    flex-flow: row wrap;
    gap: 20px;
  }

  .user-info {
    width: 350px;
  }

  .user-info * {
    font-size: 18px;
    font-weight: bold;
  }

  .user-info> :first-child img {
    width: 100px;
    height: 100px;
    border: 1px solid black;
    border-radius: 50px;
  }

  .user-info> :first-child {
    display: flex;
    flex-flow: row;
    align-items: center;
    gap: 20px;
    border: 1px solid black;
    padding: 10px;
    border-radius: 10px;
    margin-bottom: 20px;
  }

  .add-block{
    padding: 10px;
  }

  .add-block h2{
    font-size: 24px;
    color: gray;
    margin-bottom: 10px;
  }

  .add-block form , .form{
    display: flex;
    flex-flow: column;
    gap: 10px;
  }

  .add-block form input{
    padding: 2px;
    font-size: 15px;
    font-weight: normal;
  }

  .add-block button {
    padding: 10px;
    color: white;
    background: black;
  }

  .user-orders{
    width: 400px;
    height: 500px;
    padding: 10px;
  }

  .user-orders > div{
    height: 400px;
    border-radius: 10px;
    margin-top: 20px;
    background: gray;
    border-radius: 10px;
  }

  .form-item{
    padding: 15px;
    background-color: gray;
  }
</style>
<section class="container">
  <div class="user-block">
    {% if not user : %}
    <div class="user-info">
      <div>
        <img src="" alt="">
        <div>
          <p style="width: 150px; padding: 3px; background-color: gray; border-radius:5px; margin-bottom: 5px;"></p>
          <p style="width: 180px; padding: 3px; background-color: gray; border-radius:5px;"></p>
        </div>
      </div>
      <div class="add-block">
        <h2>Delivery Address</h2>
        <div class="form"  action="">
          <label for="phone" class="form-label">Phone Number</label>
          
          <div class="form-item"></div>

          <label for="street" class="form-label">Street Address</label>
          <div class="form-item"></div>

          <label for="city" class="form-label">City</label>
          <div class="form-item"></div>

          <label for="province" class="form-label">Province</label>
          <div class="form-item"></div>

          <label for="postalCode" class="form-label">Postal Code</label>
          <div class="form-item"></div>

          <label for="country" class="form-label">Country</label>
          <div class="form-item"></div>

          <button type="submit" class="btn btn-primary w-100" disabled>Save Delivery Address</button>
        </div>
      </div>
    </div>
    {% else : %}s
    <div class="user-info">
      <div>
        <img src="" alt="">
        <div>
          <p>{{user.name}}</p>
          <p style="font-size: smaller;">{{user.email}}</p>
        </div>
      </div>
      <div class="add-block">
        <h2>Delivery Address</h2>
        <form method="POST" action="{{url_for('profile.update_profile', user_id=user.id)}}">
          <label for="phone" class="form-label">Phone Number</label>
          <input type="tel" class="form-control" id="phone" name="phone" required value="{{user.phone}}">

          <label for="street" class="form-label">Street Address</label>
          <input type="text" class="form-control" id="street" name="street" placeholder="House number and street name"
            required value="{{user.street}}">

          <label for="city" class="form-label">City</label>
          <input type="text" class="form-control" id="city" name="city" required value="{{user.city}}">

          <label for="province" class="form-label">Province</label>
          <input type="text" class="form-control" id="province" name="province" required value="{{user.province}}">

          <label for="postalCode" class="form-label">Postal Code</label>
          <input type="text" class="form-control" id="postalCode" name="postal_code" required value="{{user.postal_code}}">

          <label for="country" class="form-label">Country</label>
          <input type="text" class="form-control" id="country" name="country" value="Philippines" required >
          <button type="submit" class="btn btn-primary w-100">Save Delivery Address</button>
        </form>
      </div>
    </div>
    {% endif %}
    <div class="user-orders">
      <h2>ORDERS</h2>
      <div>
        {% if not orders: %} 
        <div>
          <p>No orders yet</p>
        </div>
        {% else %}
        <style>
          .order-item{
            display: flex;
            justify-content: space-between;
            padding: 20px;
            flex-flow: row wrap;
            font-size: 15px;
            gap: 12px;
            font-weight: bold;
          }
        </style>
        <div class="orders">
          {% for item_ in orders: %}
          <div class="order-item">
            <p>ID : {{item_.id}}</p>
            <p>Item size : {{item_.item_count}}</p>
            <p>Total: Php {{item_.total}}</p>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

day_97/client/app/templates/signup.html
{% extends "base.html" %} {% block content %}

<style>
  .signup {
    width: 300px;
    padding: 20px;
    border: 2px solid gray;
    margin: 20px;
    height: fit-content;
    box-shadow: 5px 10px 0px 0px gray;
  }

  .signup-form {
    display: flex;
    flex-flow: column wrap;
  }

  .signup-form * {
    margin-top: 20px;
  }

  .signup-form input {
    border-top: 0px;
    border-left: 0px;
    border-right: 0px;
    padding: 10px;
  }

  .signup-form input:focus {
    box-shadow: none;
    border-top: 0px;
    border-left: 0px;
    border-right: 0px;
    outline: none;
  }

  .signup-form button {
    margin-top: 20px;
    padding: 10px;
  }
</style>
<section
  class="w-100 d-flex justify-content-center align-items-center container"
  style="height: 600px"
>
  <div class="signup">
    <h2>Sign-up</h2>
    <form action="" method="post" class="signup-form">
      <input type="text" name="name" placeholder="Name" />
      <input type="text" name="email" placeholder="Email" />
      <input type="password" name="password" placeholder="Password" />
      {% if error %}
      <p>{{error}}</p>
      {% endif %}
      <button>signup</button>
    </form>
  </div>
</section>

{% endblock %}

day_97/client/app/templates/test.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      input[type="number"] {
        position: relative;
        padding-right: 30px; /* Space for custom buttons */
      }

      input[type="number"]::-webkit-inner-spin-button,
      input[type="number"]::-webkit-outer-spin-button {
        opacity: 0; /* Hide default spinners */
      }
    </style>
  </head>
  <body>
    <div>
        <button onclick="increment()">▲</button>
      <input type="number" id="custom-number" min="1" max="9" step="1" value="1"/>
      <button onclick="decrement()">▼</button>
    </div>

    <script>
      const input = document.getElementById("custom-number");
      function increment() {
        input.stepUp();
      }
      function decrement() {
        input.stepDown();
      }
    </script>
  </body>
</html>